Ansible 4
Otus-DevOps-2022-05/AleksandrMalinovskiy_infra pull request #16
Opened 2022-08-14 10:54 UTC by AleksandrMalinovskiy

# Выполнено ДЗ ansible -4

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
Выполнено все согласно методичке.
Был использован Vagrant для разработки ролей
Роли были протестированны  при помощи Molecule и Testinfra
Самостоятельно
Написан тест к роли db для проверки того, что БД слушает по нужному порту (27017).
Использованы роли db и app в плейбуках packer_db.yml и packer_app.yml
Полученные роли были применены для сбора образов при помощи Packer

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-08-14 10:56 UTC, AleksandrMalinovskiy commented
Добрый день. Пытаюсь побороть пакер файлы для прохождения теста на гитхаб, но пока без успешно. Все работает на практике но тесты на гитхаб не проходят =(

2022-08-17 18:17 UTC, mrgreyves requested changes
Здравствуйте!)
Просто добавьте фейковый ключик для я облака и укажите до него путь
Пакер ругается именно на это =)

2022-08-18 06:46 UTC, AleksandrMalinovskiy commented
В папке packer есть файл key.json

2022-08-18 06:47 UTC, AleksandrMalinovskiy commented
> Здравствуйте!) Просто добавил фейковый ключик для облака и дошел до него Пакер ругается именно на это =)

В папке packer есть файл key.json

2022-08-18 10:12 UTC, closed without merging