Ansible 4
Otus-DevOps-2022-05/AleksandrMalinovskiy_infra pull request #17
Opened 2022-08-18 10:14 UTC by AleksandrMalinovskiy

# Выполнено ДЗ ansible -4

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 Выполнено все согласно методичке.
Был использован Vagrant для разработки ролей
Роли были протестированны при помощи Molecule и Testinfra
Самостоятельно
Написан тест к роли db для проверки того, что БД слушает по нужному порту (27017).
Использованы роли db и app в плейбуках packer_db.yml и packer_app.yml
Полученные роли были применены для сбора образов при помощи Packer

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-08-18 10:17 UTC, AleksandrMalinovskiy commented
Добрый день 
В предыдущий раз  пул получил от вас коментарий о том что parker ругается на ключь.
Ключ  key.json есть и в конфигах он указан но тесты не проходят хотя все работает на практике.

2022-08-23 13:46 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий
Стоит попробовать по экспериментировать с переменной которая указывает где лежит ключик
Кажется что много времени на это не уйдет

2022-08-23 13:46 UTC, mrgreyves commented on packer/variables.json.example
> +  "service_account_key_file": "./key.json",
Попробуйте удалить ./

2022-08-24 14:22 UTC, AleksandrMalinovskiy commented on packer/variables.json.example
> +  "service_account_key_file": "./key.json",
Добрый день исправил ошибку по packer

2022-08-24 15:45 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-08-25 04:21 UTC, merged